### ISSUE TITLE
Better demos: the complete kitchen sink

### ISSUE THREAD

**Issue by EHLOVader** [nazar-pc/PickMeUp#86]
Right now the [demos](http://nazar-pc.github.io/PickMeUp/) are missing a few key examples, which would be helpful for testing that code doesn't break all possible uses in the future.

So I propose a better kitchen sink.
- [x] Input, single date, single calendar
- [ ] Input, multiple date, single calendar
- [ ] Input positions top/right/bottom/left
- [ ] Input, date range, 3 calendars
- [x] Single Date, single calendar
- [x] Multiple Date, single calendar
- [x] Date Ranges, single calendar
- [ ] Month view, no day, single calendar
- [ ] Year view, no month, no day, single calendar
- [ ] Single date, 3 Calendars
- [ ] Multiple date, 3 Calendars
- [x] Date Ranges, 3 calendars
- [ ] Month view, no day, 3 calendars
- [ ] Year view, no month, no day, 3 calendars
- [ ] Static Alignment , 3 Calendars re: #79 
- [ ] Right Alignment , 3 Calendars re: #79 
- [ ] Left Alignment , 3 Calendars re: #79 
- [ ] Static Alignment, Month view, range, no day, 3 Calendars
- [ ] Static Alignment, Month view, multiple, no day, 3 Calendars
- [ ] Static Alignment, Year view,range, no day, no month, 3 Calendars
- [ ] Static Alignment, Year view,multiple, no day, no month, 3 Calendars
- [ ] 6 Calendars wrapping on screen
- [ ] Different first day of week.
- [ ] render event examples.
- [ ] change event examples

Obviously I missed many permutations but I was trying to think if all possible fringe cases where things could go wrong.

**Comment by nazar-pc** [comment]
I'm not sure that demo should be responsible for checking whether something is broken. Automated tests should do this, but there are no tests here yet.

**Comment by EHLOVader** [comment]
Absolutely.

I agree that tests should be responsible for most of this, but when in the absence of tests I feel that a reasonable set of examples which should always work would make sense for the ease of manual testing before submitting a PR.

We have a set of examples, which fits a small portion of the use cases possible from the configuration, I just think that until there is testing it would be simple to expand the examples for this purpose.

**Comment by nazar-pc** [comment]
Agree, this can be done.
BTW, it would be nice to show examples alongside with code that generates them, like here: http://getuikit.com/docs/tab.html

**Comment by EHLOVader** [comment]
:+1:  definitely. 

As I understand it the main idea of PMU is that it is framework agnostic, would you suggest adding one for layout and code formatting within the demo? UIKit or Bootstrap.

**Comment by nazar-pc** [comment]
For simplicity it can be done without any framework, there is really not that much markup (or include some from CDN, just do not include it into repository, from those two I personally prefer UIkit), for syntax highlighting [Prism](http://prismjs.com/) is a very good one (though, it seems, they do not have any CDN).

**Comment by EHLOVader** [comment]
Yeah, no need to include the framework in the repo for the demo, but having it may make it look nice.

I am sure there is a reliable third party JS cdn that has prism. Quick search turned up this... http://cdnjs.com/libraries/prism

And there is also always http://rawgit.com/

**Comment by nazar-pc** [comment]
I have nothing against using whatever framework in demo.

**Comment by ambicoder** [comment]
more demos...are required for sure...for example...how am I going to get the date selected as a string.
I tried to use eventListener...I get error though in the console.

**Comment by nazar-pc** [comment]
@ambicoder if you have difficulties, create a separate issue and add more details.
Contributions with more/better demos are definitely welcome!
